#!/usr/bin/env bash
# Raise the Kong read timeout for the Edge Functions route of this self-hosted
# runtime.
#
# The staged pipeline can legitimately spend ten minutes on one request. Kong's
# stock 150s read timeout turned every long plan into a 504, and the abandoned
# Edge execution kept running behind the client, holding journey row locks
# against the retry. The value here must stay above the worker's fetch timeout
# (700s) so the worker, not the gateway, decides when a run is over.
#
# The file lives outside this checkout and is regenerated by the runtime setup
# script, so this patch is written to be re-run: it only touches the
# functions-v1 service block and reports whether it changed anything.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUNTIME_DIR="${KAIPA_SUPABASE_RUNTIME_DIR:-$(cd "$ROOT/.." && pwd)/kaipa-supabase-docker}"
KONG_FILE="${KAIPA_KONG_CONFIG:-$RUNTIME_DIR/volumes/api/kong.yml}"
KONG_CONTAINER="${KAIPA_KONG_CONTAINER:-kaipa-supabase-kong}"
TIMEOUT_MS="${KAIPA_KONG_FUNCTIONS_TIMEOUT_MS:-780000}"
SERVICE_NAME="functions-v1"

if [[ ! -f "$KONG_FILE" ]]; then
  echo "Kong config not found: $KONG_FILE" >&2
  echo "Set KAIPA_SUPABASE_RUNTIME_DIR or KAIPA_KONG_CONFIG to point at it." >&2
  exit 2
fi

BLOCK="$(mktemp)"
PATCHED="$(mktemp)"
trap 'rm -f "$BLOCK" "$PATCHED"' EXIT

# The block runs from the service header to the next service or top-level key.
awk -v service="$SERVICE_NAME" '
  /^  - name: / { in_service = ($0 == "  - name: " service) }
  in_service && /^[^[:space:]#]/ { in_service = 0 }
  in_service { print }
  in_service && /^[[:space:]]+routes:/ { exit }
' "$KONG_FILE" > "$BLOCK"

if [[ ! -s "$BLOCK" ]]; then
  echo "Service '${SERVICE_NAME}' is missing from $KONG_FILE; refusing to guess." >&2
  exit 3
fi

if grep -qE "^[[:space:]]+read_timeout:" "$BLOCK"; then
  if grep -qE "^[[:space:]]+read_timeout:[[:space:]]*${TIMEOUT_MS}[[:space:]]*$" "$BLOCK"; then
    echo "Already patched: ${SERVICE_NAME} read_timeout is ${TIMEOUT_MS}ms"
    exit 0
  fi
  # Every read_timeout inside this one block is the endpoint's own timeout.
  sed -E "s/^([[:space:]]+)read_timeout:[[:space:]]*[0-9]+[[:space:]]*$/\1read_timeout: ${TIMEOUT_MS}/" "$BLOCK" > "$PATCHED"
else
  if ! grep -qE "^[[:space:]]+url:" "$BLOCK"; then
    echo "No read_timeout and no url in the ${SERVICE_NAME} block; refusing to guess." >&2
    exit 4
  fi
  awk -v timeout="$TIMEOUT_MS" '
    { print }
    !inserted && /^[[:space:]]+url:/ { match($0, /^[[:space:]]+/); print substr($0, 1, RLENGTH) "read_timeout: " timeout; inserted = 1 }
  ' "$BLOCK" > "$PATCHED"
fi

# Rebuild the file from the untouched prefix and suffix around the block.
BLOCK_START="$(grep -nF -m1 -x "$(head -n 1 "$BLOCK")" "$KONG_FILE" | cut -d: -f1)"
BLOCK_LINES="$(wc -l < "$BLOCK")"
{
  head -n "$((BLOCK_START - 1))" "$KONG_FILE"
  cat "$PATCHED"
  tail -n "+$((BLOCK_START + BLOCK_LINES))" "$KONG_FILE"
} > "$PATCHED.full"
# Overwrite in place so the mount keeps its original ownership and mode.
cat "$PATCHED.full" > "$KONG_FILE"
rm -f "$PATCHED.full"

echo "Set ${SERVICE_NAME} read_timeout to ${TIMEOUT_MS}ms in $KONG_FILE"

if command -v docker >/dev/null 2>&1 && docker inspect "$KONG_CONTAINER" >/dev/null 2>&1; then
  docker restart "$KONG_CONTAINER" >/dev/null
  echo "Restarted $KONG_CONTAINER"
else
  echo "Container $KONG_CONTAINER not found; restart it manually to apply the change." >&2
fi
