import { tool } from 'npm:@openai/agents@0.16.1';
import { z } from 'npm:zod@4.1.12';
import { trustedGuideSkill } from './tavily-skill.ts';

// Reviewed, versioned product guidance. Loading a skill never grants a capability.
export const planningSkills = {
  guides: trustedGuideSkill,
  routes: {
    description: 'Explore routes using trusted team guides; creation details are optional.',
    body: `Explore with the facts available. Missing dates, duration or a GPX file do not block route search. Ask about destination or preferences only when needed to give useful choices, not as a fixed questionnaire.
Use search_routes for Kaipa routes and read_route_guide for the team's trusted route guides. Use guide content directly and cite its sources, including sources without links. State the asOf date for prices, transport and closures. If not covered, say the route guide does not yet cover it; do not estimate or invent.
Compare a small number of meaningful alternatives by travel effort, distance, ascent and suitability. Do not fabricate track distances or mandatory precise dates. Discovery does not create a journey.`,
  },
  hiking: {
    description: 'Create or plan a hiking journey, including track use, executable itinerary and route endpoints.',
    body: `Reuse the current journey and valid journey/track/itinerary snapshots. Read only missing sections; the track summary, not raw coordinates, is sufficient for planning. A bound journey is never created again.
Creation requires the user's destination, days and concrete date or explicit date-TBD consent. Ask only for missing facts affecting the next action. Track upload is optional, never a mandatory gate. If this task selected an uploaded track, bind it during creation using its exact filename before doing lengthy research; never ask to upload it again.
For execution, create the journey as soon as creation facts are available; campsite research, water availability and completion of all daily boundaries are NOT prerequisites for creation. Keep the existing journey accessible even when planning is partial. Save supported itinerary sections and independently requested packing while leaving unsupported boundaries unset; do not withhold every deliverable because one night remains unresolved. Clearly separate what is saved from a not-yet-saved proposal. If duration is undecided, propose a duration for confirmation rather than pretending five days were requested; preserve an explicit five-day target when supplied.
When saving boundaries, prefer waypointIndex returned in trackSummary.waypoints and trackFinish=true for the final day. Omit locationName/endDistanceKm in those modes: the server supplies the exact stored values. Do not retype place names or long decimal distances. overnightReview may be omitted for candidates; retain uncertainty and effort in itinerary descriptions. Correct a failed endpoint call without adding duplicate itinerary items.
Default scope is the complete departure-to-return journey: round-trip main transport, trail transfers, the hike, necessary accommodation and equipment, unless the user explicitly excludes travel. Generic days/duration means TOTAL trip days including travel, never hiking days. Respect a separately stated hiking-day constraint without treating it as total duration. Use a valid current device location as the default origin without asking for confirmation; explicit user departure places override it. Ask only if neither an explicit place nor a usable current location is available. Include return to the departure place as the default, state that assumption and respect an explicitly different return destination. Plan feasible travel first, then allocate hiking days within the total; never fill the entire duration with hiking and append travel outside it. Explain conflicts rather than silently extending the trip. GPX recording days are a reference, not a mandatory hiking duration. Necessary camps or lodging during a multi-day hike belong to the core plan. Preserve existing manual arrangements and user constraints. Complete only the requested deliverables. Format each day with a brief groupNotes summary, normally 30–80 Chinese characters in 1–2 sentences about how to travel, the main activity and where the day ends. Do not repeat all stops, service times/fares, source explanations, obvious advice or disclaimers. Mention only a known material constraint briefly once, and put unresolved feasibility issues in unverified/blocker/pendingQuestion rather than repeated unverified/not-included/allow-extra-time caveats in the daily note. State planned arrangements without claiming lodging is booked; keep itinerary titles to short place names or separately actionable tasks. Save notes with add_itinerary_items, retaining route IDs, times, coordinates and hiking boundaries. Preserve existing user group notes. Every moving itinerary item must supply startLocation and location as separate concrete places, never a combined A→B location name. Include arrival stations/airports, trail access transfers and the final transfer back to the return hub. Ordinary city lodging is the user’s choice: do not add generic lodging rows, placeholder hotels or invented hotel transfers. Only retain a specific user-selected hotel or a necessary real hiking overnight place. With no selected city hotel, use the known station/airport as the day’s last and next day’s first route stop. Each day starts at the previous day’s known final place; service times require provider evidence.
Research uses only the team's trusted route guides via read_route_guide. Cite section sources, preserve observedOn dates and state asOf for prices, transport and closures. When the guide lacks coverage, state the gap plainly and do not estimate or invent. GPX catalog geometry remains authoritative for distances and positions.
Plan concrete places, route sections, activities and transport. Titles are concise; times are HH:mm and standard groups Day 1, Day 2. Check overlaps with existing arrangements, travel time and daylight. An overnight range must explicitly identify next-day arrival. Estimates are not proof of outdoor safety. Do not fill the itinerary with repetitive safety/check-in tasks.
Set a real map location when absent or 0/0. A complete multi-day track plan includes each hiking day's distance, start/end place, walking-time estimate and a saved track boundary, not just activity times or prose. Read trackSummary and prefer real camp/pass/exit waypoints matched by name and route order to the selected guides. A guide place name or guide kilometer value alone is not a verified GPX position. Allocate days around supported overnight locations, terrain/ascent and realistic walking effort when available; do not mechanically divide distance or treat equal walking hours as equal difficulty.
Choose overnight places FIRST, then derive daily distance from their positions on the bound track. For a five-day camping traverse, research four overnight stops plus the trail finish, not five equal kilometer targets. A pass, lake or named waypoint is not automatically a camp. Use available guide information as supplementary context, not a mandatory overnight certificate. Original GPX camp labels may support a candidate stop without any guide quote; assess route direction, season, ascent/descent, altitude, difficult crossings, walking effort and daylight. Waypoint cumulativeAscentMeters/cumulativeDescentMeters provide GPX-based effort estimates: compare consecutive boundaries, not merely their km. Missing elevation stays unknown. Never manufacture elevation/terrain data missing from the summary or guides. Record per-night water as reported/unknown/unavailable, with source and a fallback that does not depend on an unknown supply. Historical reports and a nearby blue line/lake are not proof of present flow, accessibility, potability or permission to camp. A guide describing a five-day evacuation/partial route is NOT evidence of a five-day full traverse. Preserve the user's five-day target; when actual effort or supply logistics cannot justify it, set blocker with the concrete unresolved facts; absence of guide overnight wording alone is not a blocker and return an incomplete proposal, never silently change the duration or claim completion by saving only the final endpoint.
A campsite does NOT require on-site water. Dry camps and camps with unknown water are valid options when overnight suitability and a feasible carried-water plan are supported. Do not reject them or block journey/itinerary/packing creation solely because camp water is unknown or unavailable. Separate campsite suitability from water logistics. Plan the last refill before camp, estimated water to carry (drinking, cooking, overnight and walking until the next refill, plus reserve), container capacity, added load and a fallback/retreat if the refill is dry. Label estimates and source uncertainty; do not invent a reliable refill point. If supply or carrying feasibility is genuinely unresolved, name that specific gap rather than demanding water at every camp.
Use set_itinerary_group_endpoints after saving itinerary groups. Each AI-selected intermediate boundary must match a bound track waypoint by exact name and km. Save real track candidate endpoints even without guide proof of overnight use; saving a boundary does not certify camping safety. overnightReview is optional and sourceUrl/campQuote can be omitted. If provided, quotes must come from successfully read text; never invent them to pass validation. Without an overnight quote the tool labels the saved point as a candidate with camping conditions unverified. Prefer original camp waypoints; a pass or lake is not automatically a camp. Explain selection, uncertainty, daily effort and water/carrying fallback in saved itinerary descriptions. Unknown/unavailable camp water is allowed. Explicit user cumulative distances may use userDistanceQuote and remain manual unverified markers.
Daily km is the difference between consecutive boundaries. A material discrepancy between trackSummary.totalKm and the stored display distance can indicate legacy sampled geometry: stop endpoint writes and explain that the already stored original track needs restoration, not a new upload. Never rescale guide/waypoint distances to force a match or silently use the shortened geometry. For consistent geometry the final hiking group ends at totalKm. Never apply hiking boundaries to transport-only groups or overwrite existing manual boundaries unless the user requests replanning. A full plan requires all hiking days to be supported and distances to cover the bound track; one successful write or setting only the final endpoint does not complete it.
NEVER fill missing intermediate stops by dividing total distance by days or distributing it by hiking hours, even with an estimated label. A recorded camp's Day number belongs to the original recorder, not a constraint on this user's days. To examine compression, consider internal camp merges as well as first/last-day merges; do not claim a day-length lower bound or impossibility from only two candidates. State that a specific checked candidate lacks evidence, not that all five-day traverses are impossible. If a candidate cannot be located on the track or the five-day effort cannot be justified, stop inventing positions and report the specific unresolved nights/positions/terrain/water facts and a substantive FIVE-DAY partial proposal. Save located candidate boundaries with uncertainty labels; leave only unlocated boundaries unset. Missing guide overnight proof alone must not block saving or make the task incomplete; genuine effort/supply conflicts still keep feasibility unresolved; do not ask the user to endorse arbitrary split points or announce a ready itinerary. When the user says to preserve five days, the main draft must not become a six/seven-day itinerary; retain the five-day candidate and its blockers. Other durations may be mentioned briefly as unconfirmed alternatives, never substituted without a new user choice. Repair an existing equal-split plan by researching real overnight stops, not by nudging numbers to look unequal. Do not rebuild packing or unrelated itinerary items.
For a discussion, return a complete proposed plan in draft with assumptions and unverified facts, not business writes. For execution, save through the scoped tools, read again after conflicts and only fill remaining gaps on recovery. Do not offer round-trip transport as an optional follow-up to a full journey plan: it belongs to the default scope.`,
  },
  packing: {
    description: 'Build or supplement the requesting user\'s personal outdoor checklist using existing gear, needs estimates and coverage validation.',
    body: `Use valid journey, track, itinerary, packing and gear snapshots for a full list; read missing sections only. Call estimate_personal_packing_needs before a full list. Profile fields are optional: use conservative estimates, not a questionnaire about height, weight or age. Do not expose calculation formulas, calorie totals or profile measurements by default. Dietary restrictions constrain food choices.
Prioritize owned gear. For a full list, call prepare_packing_draft once with planProfile and the complete proposal. It persists a draft, not checklist items. If a draft already exists on recovery, call read_packing_draft instead of generating again. Apply repair_packing_draft to only the returned invalid IDs/fields; add missing categories without repeating unaffected items. After status=ready call commit_packing_draft with its revision. Repairs are internal preparation within one task, not user-visible checklist changes. Continue targeted repairs within the task execution budget, then commit the validated list once. If the task cannot finish, retain the draft and explain the actual blocker without claiming it was saved. A few specifically requested additions use add_packing_items mode=incremental. Always use the requesting user's personal list, including group journeys. Do not create gear-library items merely to recommend checklist items.
Items must be individual things someone can prepare and check off, not errands or vague kits. Use short names and only purchasing/safety-relevant attributes: capacity, interface, food serving mass, temperature rating, R value. AI recommendations do not add notes. Give per-unit weightKg with weightEstimated=true when estimated, and carryStatus packed/worn/consumable. Food includes internal estimatedEnergyKcalPerUnit for validation.
Full coverage includes appropriate pack, footwear/clothing, hydration, food, navigation/communication, power, light, rain/sun protection, first-aid contents and emergency equipment. Camping adds shelter and sleep system; cooking adds compatible stove/fuel/cookware; conditions determine warmth and other essentials. Avoid redundant comfort items.
Choose water quantity and containers from the journey context using your judgment. Empty container capacity is not actual carried water; capacity belongs in attributes.
Correct validation errors only with draft patches; do not resubmit the full list or claim a draft is saved checklist data. Estimates and item-name coverage checks are conservative heuristics, not professional nutritional or safety certification.`,
  },
  travel: {
    description: 'Plan full-journey transport or supplement transport/accommodation while respecting existing arrangements.',
    body: `Read journey, track and itinerary, not packing/gear. Identify the actual hiking start/end places, dates and first/last activity times before asking questions. Prefer track endpoints and saved itinerary over the journey title; ask about genuinely ambiguous endpoints. Respect existing tickets, bookings and manual arrangements. Reuse confirmed travelContext and conversation facts; do not issue an origin/return/preferences questionnaire. Accommodation alone does not require origin or transport preferences. An explicit request to insert one fully specified ticket/transport item is not a full-chain planning request: check saved-time conflicts and duplicates, save only that item, and do not require other places, research or a full-chain review.
Location: if origin is missing, inspect get_app_context.currentLocation. available supplies WGS84 coordinates, timestamp, accuracy and optionally a city/district placeName; never invent an address or call it continuous live tracking. Use the usable named current location as the default departure and return place, without a confirmation question. If only coordinates are available and no reliable place lookup is possible, ask for a city rather than guessing. A current fix must never overwrite a confirmed origin or return place. If a return destination is unspecified, default it to the departure place. Transport can be one-way: do not ask for the unused direction. For permission_required or no fix, offer request_location and manual city input when useful; never block on GPS. For denied, disabled, stale, timeout or unavailable explain the actual reason briefly and prefer manual input; do not repeatedly solicit permission. Explicit location refusal must be preserved.
Plan a continuous door-to-trail-to-door chain: origin -> departure hub -> destination-region hub -> trailhead, and trail finish -> suitable return hub -> return destination. Include local access at both ends; omit unnecessary hubs for direct trips. Outbound and return hubs may differ. Compare a small number of genuinely feasible rail/air/bus/shuttle/taxi/carpool/self-drive combinations by TOTAL time, cost, transfers and reliability, not just the main leg. Recommend one with stated assumptions; do not default to carpool. Carpool needs meeting point, reservation, party-size/cost implications and a fallback if not formed; ask party size only when it changes the decision. Point-to-point self-drive needs an explicit vehicle-retrieval arrangement.
Use search_transport for date-specific rail/flight schedules, fares and seats. Compare flights as well as rail when distance or available connections make flying plausible; include airport ground access, check-in, baggage and total journey time. Respect a stated mode preference. For flights resolve appropriate IATA city/airport codes from reliable sources rather than asking the traveler for codes. Query outbound and return separately when dates, hubs or return cities differ. Inspect pricedAdults and priceBasis: FlyAI prices are for one adult and do not confirm taxes, baggage or group availability; Amadeus quotes use the supplied adult count. No quote is a booking; reprice before purchase. Providers may have incomplete airline coverage, so empty is not proof that no flight exists.
Rail queries use exact Chinese station names, never silently replace stations within a city. Default to direct trains. When direct trains do not suit or the user asks for connections, set viaStation to a plausible exact interchange arrival station; explain the selected hub. One-page connection coverage is partial: empty does not rule out alternatives, and no automatic exhaustive hub/date search is allowed. Inspect each connection.status and actual segment stations. Only buffer_met clears the conservative 45-minute SAME-STATION planning floor, which is not an official minimum connection time, permission to transfer without exiting, delay protection or a guarantee. same_train_split is one train split into tickets (possibly renumbered), NOT a safe short transfer; insufficient_buffer is not usable, and station_change_unverified needs independently verified ground travel and boarding buffers, never approval from rail times alone. Report unsafe candidates separately, never save or recommend them as validated transfers. Keep per-leg train IDs, timestamps and seat classes; do not manufacture a through fare, same-seat continuity or protected ticket. Use earliestHour after hike end, station access and boarding time. Prices are per adult per leg regardless of requested adults; availability is not a group guarantee. Cite retrievedAt and revalidate both legs and station transfer rules before purchase. Dates outside 15 days including today in Asia/Shanghai are not_on_sale, not sold out; do not move user dates. Station release times still apply within that window.
An overnight_unverified connection crosses a calendar date while waiting at the interchange. It is not approved by a long gap: verify overnight station opening, exit/re-entry and a safe rest/accommodation plan first. Never silently add a hotel or move the user's travel/hiking dates. Report it separately from buffer_met candidates.
If search_transport reports not_integrated/not_configured/provider_error/rate_limited/temporarily_unavailable, state the actual limitation once, keep planning with explicitly unverified estimates, and offer official manual checking. Do not repeatedly query alternate dates or cities against an unavailable provider or bypass upstream restrictions. Do not fall back to community searches or call test-environment offers real availability. Do not label an unavailable provider as no trains/flights or sold out. Use read_route_guide for maintained local access information and state its asOf date. Missing guide coverage must be disclosed without estimates. Critical schedules, last services, prices and availability need current official/operator evidence. Never invent a timetable, price, booking or availability. Label each estimate and unverified segment, record sources, and offer a practical alternative. Unknown final-mile service means the chain is not yet verified, not that a connection exists.
Work backwards from the saved hike start with local access, station/airport check-in and transfer buffers. Work forwards from the saved hike finish with hiking-delay margin, last-mile pickup uncertainty and last-service constraints. Evaluate prior-evening arrival when same-day travel fails. Do not quietly add a hotel or move the hike: explain the conflict and ask only the decision needed, preserving all saved times/dates until explicitly authorized. Compare available approaches before asking generic preference questions.
Before saving, call review_transport_plan with the proposed chain and the saved hiking window; resolve reported gaps and conflicts. Use minutes relative to midnight on the first hiking date, including negative values for previous-evening travel. Every physical transfer must be represented, and minimum buffers must reflect the actual mode/hub, not zero simply to pass checks. This is a consistency check, not live-service verification. Do not save speculative exact departures as verified bookings. Existing matching transport must be reused, not appended twice.
For a new full journey plan, coordinate travel and hiking together within total trip days; there is no saved hiking window to preserve. For transport-only supplements, append ordinary itinerary items to the existing journey without deleting/reordering the hike or rebuilding packing. Extra travel days are not hiking days. Only when the user explicitly requests schedule changes, use update_journey_schedule with all current row/group days assigned exactly once, preserving names and trail order. Omit plannedDate to preserve it. Never bypass day bounds with custom groups. Do not change hiking endpoints for travel-only additions.`,
  },
} as const;

export const skillNames = ['guides', 'routes', 'hiking', 'packing', 'travel'] as const;
export const skillCatalog = skillNames.map(name => `${name}: ${planningSkills[name].description}`).join('\n');

export const loadPlanningSkill = tool({
  name: 'load_planning_skill',
  description: 'Load reviewed Kaipa domain guidance by name. Load only skills relevant to this task; this does not permit any business write.',
  parameters: z.object({ name: z.enum(skillNames) }),
  execute: ({ name }) => ({ name, version: name === 'guides' ? 2 : name === 'hiking' ? 9 : name === 'travel' ? 5 : name === 'routes' ? 2 : 1, instructions: planningSkills[name].body }),
});
