export const routeGuideCopy = {
  zh: {
    plans: '怎么走这条线', choosePace: '选择适合你的节奏', draft: 'Kaipa 行程参考', draftNote: '按季节与体能调整，具体路段与住宿需确认', viewPlan: '查看行程与装备', draftDetail: '出发前确认具体路段、住宿或营地与补给；创建旅程后，可按体能与天气继续调整。',
    conditions: '近期实况', allConditions: '查看实况', shareCondition: '分享近期实况', shareConditionPlaceholder: '写下你刚看到的路线情况…', publishCondition: '发布', pendingCondition: '已提交，审核通过后会显示', addMedia: '添加媒体', mediaLimit: '最多 9 个媒体；单个文件不超过 50 MB，视频不超过 15 秒', mediaLimitShort: '最多9个　单个50 MB　视频15秒', conditionsIntro: '来自路线现场的图片、视频与文字记录', conditionsEmptyHint: '有新的现场记录后，会在这里展示到访时间、所在路段和发布来源。', weather: '路线附近天气', noReports: '还没有近期实况', noReportsHint: '路线封面用于了解景观，不能代表当前通行情况。', routePhotos: '路线照片', unknownPhotoDate: '拍摄日期未提供', weatherUnavailable: '暂无天气信息', retry: '重试', weatherSource: 'Open-Meteo · 路线附近位置预报', weatherScope: '预报对应路线附近坐标，不代表整条山地路线。出发前还需核实通行情况。', updated: '更新', rain: '降水概率', wind: '风速',
    guides: '大家的攻略', allGuides: '全部攻略', noGuides: '暂时还没有攻略', includes: '含每日行程 · 装备清单', recommended: '推荐', helpfulSort: '最多帮助', updatedSort: '最近更新', all: '全部走法', day: '轻装', stay: '住宿', camp: '露营', autumn: '秋季', spring: '春季', helpful: '觉得有帮助', helpfulMarked: '已标记有帮助', travelDate: '出行于', publishedDate: '发布于', updatedDate: '更新于',
    itinerary: '行程', equipment: '装备', review: '复盘', dayPlan: '每日行程', gearTitle: '装备清单', gearNote: '按所选行程、住宿方式与天气调整；饮水量、睡袋温标等需结合实际条件确定。', communityGearNote: '这份攻略的装备清单与携带建议，可结合自己的行程、季节和天气调整。', reviewTitle: '如果再走一次', createPlan: '用此方案创建旅程', createGuide: '以此攻略创建旅程', referencePlan: '参考方案', guideDetail: '攻略详情', weatherDetail: '路线天气', distance: '路线里程', ascent: '累计爬升', difficulty: '路线难度', close: '关闭', back: '返回',
    shareGuide: '分享攻略', shareText: '分享至', wechat: '微信好友', copyText: '复制文本', textCopied: '攻略文本已复制', exportGuide: '导出攻略', guidePoster: '攻略长图', guidePosterHint: '完整行程、装备与复盘', saveToAlbum: '保存到相册', saved: '已保存', permissionRequired: '请允许访问相册后再保存', exportText: '导出文本', exportChecklist: '导出装备清单', exportFailed: '导出失败，请重试', authorLabel: '作者', totalWeight: '总重', exportNote: '内容仅供参考，请结合实际天气、通行条件和体能判断。',
    importing: '正在保存行程与装备…', imported: '旅程已创建，行程与装备已带入', importFailed: '旅程已创建，但行程与装备未能带入，请稍后重试', templateHint: '创建时将带入这份方案的行程与装备清单', templateDays: '请保持方案天数，或返回选择其他方案', templateMismatch: '路线已改变，请重新选择参考方案', templateManual: '按参考方案创建',
  },
  en: {
    plans: 'Ways to plan this route', choosePace: 'Choose your pace', draft: 'Kaipa reference plan', draftNote: 'Adjust for season and fitness; verify sections and lodging.', viewPlan: 'View itinerary & gear', draftDetail: 'Verify actual sections, lodging or camps and supplies before departure. Adapt the trip to fitness and weather.',
    conditions: 'Recent observations', allConditions: 'View observations', shareCondition: 'Share an observation', shareConditionPlaceholder: 'Write what you just saw on the route…', publishCondition: 'Publish', pendingCondition: 'Submitted. It will appear after review.', addMedia: 'Add media', mediaLimit: 'Up to 9 items; 50 MB per file and 15 seconds per video', mediaLimitShort: '9 max　50 MB/item　15s video', conditionsIntro: 'Photos, videos and written observations from the trail', conditionsEmptyHint: 'New observations will show the visit date, trail section and source here.', weather: 'Weather near the route', noReports: 'No recent observations yet', noReportsHint: 'Cover photos show scenery, not current access conditions.', routePhotos: 'Route photos', unknownPhotoDate: 'Capture date unavailable', weatherUnavailable: 'Weather unavailable', retry: 'Retry', weatherSource: 'Open-Meteo · forecast near the route', weatherScope: 'This forecast covers coordinates near the route, not the entire mountain trail. Verify access separately.', updated: 'Updated', rain: 'Rain probability', wind: 'Wind',
    guides: 'Community guides', allGuides: 'All guides', noGuides: 'No guides yet', includes: 'Daily itinerary · Packing list', recommended: 'Recommended', helpfulSort: 'Most helpful', updatedSort: 'Recently updated', all: 'All styles', day: 'Day pack', stay: 'Lodging', camp: 'Camping', autumn: 'Autumn', spring: 'Spring', helpful: 'found this helpful', helpfulMarked: 'Marked helpful', travelDate: 'Trip', publishedDate: 'Published', updatedDate: 'Updated',
    itinerary: 'Itinerary', equipment: 'Gear', review: 'Reflection', dayPlan: 'Daily itinerary', gearTitle: 'Packing list', gearNote: 'Adapt to the itinerary, lodging and weather. Water volume and sleeping bag ratings depend on actual conditions.', communityGearNote: 'Packing list and gear advice for this guide. Adapt to your itinerary, season and weather.', reviewTitle: 'Next time', createPlan: 'Create a trip from this plan', createGuide: 'Create a trip from this guide', referencePlan: 'Reference plan', guideDetail: 'Guide details', weatherDetail: 'Route weather', distance: 'Distance', ascent: 'Ascent', difficulty: 'Difficulty', close: 'Close', back: 'Back',
    shareGuide: 'Share guide', shareText: 'Share to', wechat: 'WeChat', copyText: 'Copy text', textCopied: 'Guide text copied', exportGuide: 'Export guide', guidePoster: 'Guide image', guidePosterHint: 'Full itinerary, gear and reflection', saveToAlbum: 'Save to album', saved: 'Saved', permissionRequired: 'Allow photo access to save', exportText: 'Export text', exportChecklist: 'Export packing list', exportFailed: 'Export failed. Please retry.', authorLabel: 'Author', totalWeight: 'Total weight', exportNote: 'For reference. Adapt to actual weather, access conditions and your fitness.',
    importing: 'Saving itinerary and gear…', imported: 'Trip created with itinerary and gear', importFailed: 'Trip created, but itinerary and gear could not be imported. Please retry later.', templateHint: 'The itinerary and packing list will be added when you create this trip.', templateDays: 'Keep the plan’s duration or choose another plan.', templateMismatch: 'The route changed. Please select a plan for this route.', templateManual: 'Create from reference plan',
  },
} as const;
