-- Fill imported routes with best-season metadata (best_months + season_note).
--
-- Hand-curated in scripts/route-seasons.json; this migration is generated by
-- scripts/generate-route-seasons.mjs on 2026-09-19.
-- Regenerate with:
--   node scripts/generate-route-seasons.mjs
--
-- Effect:
--   1. adds the season columns to routes (idempotent)
--   2. fills them for every imported route

do $$ begin
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='routes' and column_name='best_months') then
    alter table routes add column best_months int4[];
  end if;
  if not exists (select 1 from information_schema.columns where table_schema='public' and table_name='routes' and column_name='season_note') then
    alter table routes add column season_note text;
  end if;
end $$;

update routes set best_months = '{5,6,7,8,9,10}', season_note = '6-7月杜鹃花海；雨季云雾多' where id = 'trk001';
update routes set best_months = '{5,6,7,8,9,10}', season_note = null where id = 'trk002';
update routes set best_months = '{4,5,9,10}', season_note = '春秋温度适宜；夏季高温，冬季风沙严寒' where id = 'trk003';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '5月前、10月后垭口积雪深' where id = 'trk004';
update routes set best_months = '{6,7,8,9}', season_note = '7-8月最稳；需翻冰湖冰川' where id = 'trk005';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = '夏季多暴雨山洪，慎行重装' where id = 'trk006';
update routes set best_months = '{6,7,8,9}', season_note = '6-8月花海最佳' where id = 'trk007';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '10月彩林最佳；6-7月花海' where id = 'trk008';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；10月秋色最佳' where id = 'trk009';
update routes set best_months = '{4,5,6,9,10,11}', season_note = '雨季注意峡谷山洪；冬季阴面有冰' where id = 'trk010';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '7-8月雨雪多；10月后垭口易封' where id = 'trk011';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '6-7月花海最佳' where id = 'trk012';
update routes set best_months = '{6,7,8,9}', season_note = '冰川线海拔高，选稳定天气' where id = 'trk013';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '6-7月花海最佳' where id = 'trk014';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；10月秋色最佳' where id = 'trk015';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；看主峰选春秋' where id = 'trk016';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = '夏季炎热多雨，慎行重装' where id = 'trk017';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = '春秋最宜；夏季注意洪水' where id = 'trk018';
update routes set best_months = '{5,6,9,10,11}', season_note = '7-8月雨季' where id = 'trk019';
update routes set best_months = '{5,6,9,10,11}', season_note = '7-8月雨季' where id = 'trk020';
update routes set best_months = '{5,6,7,8,9,10}', season_note = null where id = 'trk021';
update routes set best_months = '{3,4,5,9,10,11}', season_note = '冬季西海大峡谷可能封闭' where id = 'trk022';
update routes set best_months = '{3,4,5,6,9,10,11}', season_note = null where id = 'trk023';
update routes set best_months = '{5,6,7,8}', season_note = '6-7月草原花海最佳' where id = 'trk024';
update routes set best_months = '{5,6,9,10,11}', season_note = '7-8月雨季，难见卡瓦格博' where id = 'trk025';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；9-10月湖色最佳' where id = 'trk026';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；9-10月湖色最佳' where id = 'trk027';
update routes set best_months = '{7,8,9}', season_note = '仅7-9月窗口，其余时间大雪封山' where id = 'trk028';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季；看冰川湖需晴天' where id = 'trk029';
update routes set best_months = '{3,4,5,9,10,11}', season_note = '10-11月最稳；6-8月雨季，12-2月高寒' where id = 'trk030';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '9-10月彩林最佳' where id = 'trk031';
update routes set best_months = '{5,6,9,10,11}', season_note = '7-8月雨季；垭口天气多变' where id = 'trk032';
update routes set best_months = '{6,7,8,9}', season_note = null where id = 'trk033';
update routes set best_months = '{3,4,5,10,11}', season_note = '10-11月最稳；6-9月雨季，12-2月垭口雪大' where id = 'trk034';
update routes set best_months = '{6,7,8}', season_note = '年保玉则景区已关闭多年，出发前确认政策' where id = 'trk035';
update routes set best_months = '{6,7,8}', season_note = '年保玉则景区已关闭多年，出发前确认政策' where id = 'trk036';
update routes set best_months = '{6,7,8,9}', season_note = '全线海拔4700m+，仅6-9月窗口' where id = 'trk037';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '9-10月彩林最佳' where id = 'trk038';
update routes set best_months = '{6,7,8,9}', season_note = '海拔高天气多变，垭口注意风雪' where id = 'trk040';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季' where id = 'trk041';
update routes set best_months = '{3,4,5,9,10,11}', season_note = '冬季云海雾凇亦佳，注意台阶结冰' where id = 'trk042';
update routes set best_months = '{5,6,7,8,9,10}', season_note = null where id = 'trk043';
update routes set best_months = '{5,6,9,10}', season_note = '7-8月雨季' where id = 'trk044';
update routes set best_months = '{4,5,6,9,10,11}', season_note = '7-8月雨季天气不稳；冬季雪厚冲顶难' where id = 'trk045';
update routes set best_months = '{4,5,6,9,10,11}', season_note = '7-8月雨季；冬季雪厚风大' where id = 'trk046';
update routes set best_months = '{5,6,9,10}', season_note = '有技术路段，选春秋稳定窗口' where id = 'trk047';
update routes set best_months = '{4,5,9,10,11}', season_note = '看云海日出避开雨季' where id = 'trk048';
update routes set best_months = '{5,6,7,8,9,10}', season_note = null where id = 'trk049';
update routes set best_months = '{6,7,8,9}', season_note = '8-9月最稳；垭口海拔5000m+' where id = 'trk050';
update routes set best_months = '{6,7,8,9}', season_note = '8-9月最稳；垭口海拔5000m+' where id = 'trk051';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '9-10月秋色最佳；10月后高山区可能封山' where id = 'trk052';
update routes set best_months = '{6,7,8,9}', season_note = '6-8月花海最佳' where id = 'trk053';
update routes set best_months = '{6,7,8,9}', season_note = '6-9月窗口；9月后达坂积雪、河水刺骨' where id = 'trk055';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '7-8月最宜；10月后风雪降温' where id = 'trk056';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '7-8月最宜；10月后风雪降温' where id = 'trk057';
update routes set best_months = '{4,5,6,7,8,9,10,11}', season_note = '5-10月草甸最佳；山顶风大注意保暖' where id = 'trk058';
update routes set best_months = '{4,5,6,7,8,9,10,11}', season_note = '5-10月草甸最佳；山顶风大注意保暖' where id = 'trk059';
update routes set best_months = '{5,6,7,8,9,10}', season_note = '夏秋季节适宜；高海拔垭口注意天气变化' where id = 'trk039';
update routes set best_months = '{5,6,9,10}', season_note = '9-10月最稳；7-8月雨季' where id = 'trk060';
update routes set best_months = '{6,7,8,9}', season_note = '翻木扎尔特冰川，7-8月最稳' where id = 'trk061';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = '秋冬最宜；夏季炎热多台风' where id = 'trk062';
update routes set best_months = '{3,4,5,9,10,11}', season_note = '7-9月雨季塌方风险高' where id = 'trk063';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = null where id = 'trk064';
update routes set best_months = '{5,6,9,10,11}', season_note = '秋冬泡温泉赏雪景；7-8月雨季' where id = 'trk065';
update routes set best_months = '{5,6,9,10}', season_note = '10月秋色最佳；7-8月雨季' where id = 'trk066';
update routes set best_months = '{5,6,9,10}', season_note = '10月秋色最佳；7-8月雨季' where id = 'trk067';
update routes set best_months = '{5,6,9,10}', season_note = '夏秋季节较适宜' where id = 'trk068';
update routes set best_months = '{4,5,9,10}', season_note = '春秋温度适宜；夏季高温，冬季风沙严寒' where id = 'trk054';
update routes set best_months = '{3,4,5,10,11}', season_note = '夏季台风季慎行' where id = 'trk069';
update routes set best_months = '{5,6,9,10,11}', season_note = '10-11月日照金山最稳；7-8月雨季' where id = 'trk070';
update routes set best_months = '{10,11,12,1,2,3,4}', season_note = null where id = 'trk071';
update routes set best_months = '{6,7,8,9}', season_note = '8-9月最稳；6月前垭口有雪' where id = 'trk072';
update routes set best_months = '{6,7,8,9,10}', season_note = '7-8月花海；6月前垭口有雪' where id = 'trk073';
update routes set best_months = '{5,6,9,10}', season_note = '5月、10月窗口最佳；7-8月雨季' where id = 'trk074';
