-- Fill imported routes with real region names (省 · 市) reverse-geocoded
-- from each track's start point via the AMap regeo API.
--
-- Generated by scripts/geocode-route-regions.mjs on 2026-09-19.
-- Regenerate with:
--   node scripts/geocode-route-regions.mjs
-- The stem -> region map is also persisted in scripts/route-regions.json so
-- scripts/import-hiking-routes.mjs can embed regions offline.

update routes set region = '云南 · 迪庆' where id = 'trk001';
update routes set region = '云南 · 迪庆' where id = 'trk002';
update routes set region = '内蒙古 · 阿拉善' where id = 'trk003';
update routes set region = '四川 · 阿坝' where id = 'trk004';
update routes set region = '新疆 · 乌鲁木齐' where id = 'trk005';
update routes set region = '广东 · 清远' where id = 'trk006';
update routes set region = '四川 · 阿坝' where id = 'trk007';
update routes set region = '四川 · 甘孜' where id = 'trk008';
update routes set region = '四川 · 凉山' where id = 'trk009';
update routes set region = '河南 · 新乡' where id = 'trk010';
update routes set region = '西藏 · 阿里' where id = 'trk011';
update routes set region = '四川 · 甘孜' where id = 'trk012';
update routes set region = '四川 · 甘孜' where id = 'trk013';
update routes set region = '四川 · 甘孜' where id = 'trk014';
update routes set region = '四川 · 甘孜' where id = 'trk015';
update routes set region = '四川 · 甘孜' where id = 'trk016';
update routes set region = '广西 · 桂林' where id = 'trk017';
update routes set region = '广西 · 桂林' where id = 'trk018';
update routes set region = '云南 · 迪庆' where id = 'trk019';
update routes set region = '云南 · 迪庆' where id = 'trk020';
update routes set region = '四川 · 阿坝' where id = 'trk021';
update routes set region = '安徽 · 黄山' where id = 'trk022';
update routes set region = '安徽 · 宣城' where id = 'trk023';
update routes set region = '新疆 · 伊犁' where id = 'trk024';
update routes set region = '云南 · 迪庆' where id = 'trk025';
update routes set region = '西藏 · 山南' where id = 'trk026';
update routes set region = '西藏 · 山南' where id = 'trk027';
update routes set region = '新疆 · 昌吉' where id = 'trk028';
update routes set region = '四川 · 甘孜' where id = 'trk029';
update routes set region = '尼泊尔' where id = 'trk030';
update routes set region = '陕西 · 安康' where id = 'trk031';
update routes set region = '云南 · 迪庆' where id = 'trk032';
update routes set region = '新疆 · 伊犁' where id = 'trk033';
update routes set region = '尼泊尔' where id = 'trk034';
update routes set region = '青海 · 果洛' where id = 'trk035';
update routes set region = '青海 · 果洛' where id = 'trk036';
update routes set region = '西藏 · 拉萨' where id = 'trk037';
update routes set region = '陕西 · 商洛' where id = 'trk038';
update routes set region = '四川 · 阿坝' where id = 'trk039';
update routes set region = '甘肃 · 张掖' where id = 'trk040';
update routes set region = '西藏 · 林芝' where id = 'trk041';
update routes set region = '江西 · 上饶' where id = 'trk042';
update routes set region = '四川 · 甘孜' where id = 'trk043';
update routes set region = '四川 · 凉山' where id = 'trk044';
update routes set region = '四川 · 阿坝' where id = 'trk045';
update routes set region = '四川 · 阿坝' where id = 'trk046';
update routes set region = '四川 · 阿坝' where id = 'trk047';
update routes set region = '四川 · 甘孜' where id = 'trk048';
update routes set region = '四川 · 阿坝' where id = 'trk049';
update routes set region = '西藏 · 昌都' where id = 'trk050';
update routes set region = '西藏 · 昌都' where id = 'trk051';
update routes set region = '陕西 · 西安' where id = 'trk052';
update routes set region = '四川 · 阿坝' where id = 'trk053';
update routes set region = '内蒙古 · 阿拉善' where id = 'trk054';
update routes set region = '新疆 · 伊犁' where id = 'trk055';
update routes set region = '山西 · 忻州' where id = 'trk056';
update routes set region = '山西 · 忻州' where id = 'trk057';
update routes set region = '江西 · 萍乡' where id = 'trk058';
update routes set region = '江西 · 萍乡' where id = 'trk059';
update routes set region = '西藏 · 日喀则' where id = 'trk060';
update routes set region = '新疆 · 阿克苏' where id = 'trk061';
update routes set region = '香港 · 大埔' where id = 'trk062';
update routes set region = '云南 · 迪庆' where id = 'trk063';
update routes set region = '广西 · 南宁' where id = 'trk064';
update routes set region = '四川 · 甘孜' where id = 'trk065';
update routes set region = '四川 · 甘孜' where id = 'trk066';
update routes set region = '四川 · 甘孜' where id = 'trk067';
update routes set region = '四川 · 甘孜' where id = 'trk068';
update routes set region = '浙江 · 温州' where id = 'trk069';
update routes set region = '云南 · 迪庆' where id = 'trk070';
update routes set region = '广西 · 柳州' where id = 'trk071';
update routes set region = '甘肃 · 甘南' where id = 'trk072';
update routes set region = '甘肃 · 甘南' where id = 'trk073';
update routes set region = '西藏 · 日喀则' where id = 'trk074';
